### PR TITLE
Search count spell status

### PR DESCRIPTION
**Pull request by bobbleclank**
Add optional search count and spell status.

### CODE REVIEW

**Comment by bobbleclank** [comment]
This implementation does not include search count nor spell status in the inactive status line.

I tested having search count in the inactive status line however I wasn't convinced it was useful when jumping around windows and doing different searches. More testing and usage is probably needed before making a decision to include search count in the inactive status line. I would appreciate your thoughts on this?

For spell status, it might be nice to display the window's spell status in the inactive status line, since each window remembers if spell is on or off and continues to display spelling errors when inactive (and spell is on). However, simply copying the current spell status implementation to the inactive window did not work, where the current active window's spell status was displayed in each inactive window. I have no idea how complicated it would be to have this work correctly. It's probably better to first test drive only having spell status for the active window, to see if it's really needed in inactive windows.

For the layout in the readme, I added a single section `W`, even though there is a separator between search count and spell status. I checked where separators are currently used, where for the right side found that they are used between sections `X` and `Y`, and, `Y` and `Z`. However for the left side found that there is only one separator between `B` and `C`. Note, I realise it wouldn't make sense to have a separator between `A` and `B`, so a separator is really only missing between `C` and `D` when mapping back to the layout sections. Then, I'm hoping it is okay to add a single section `W` which includes a separator within it.

I welcome any feedback on the above points, other implementation details, and added documentation.

**Comment by bluz71** [comment]
Nice work.

Upon review all seems fine. `W` is correct for the section.

I agree with spell & search count being displayed only for the active `statusline`. It should be noted that I use Neovim 99% of the time, and I have global statusline enabled, so I don't really have inactive `statusline` in my setup (choice a personal choice).

I will give this a quick run and see if anything pops up. I will need to port this over to [linefly](https://github.com/bluz71/nvim-linefly).

I also need to implement Macro recording status for both plugins.

Thanks again, really nice PR.

**Comment by bluz71** [comment]
After a test run, all good; very nice look too.

**Comment by bobbleclank** [comment]
Thank you for merging! And thank you for the tweaks on the search count implementation.

> I use Neovim 99% of the time, and I have global statusline enabled

It's time I got back to my Neovim configuration, will move to `linefly` and try the global status line.

If you have a few minutes, could you please explain what `'%*'` does?

Would you happen to have a good resource or reference for Vim script? Half a year ago I found a guide at IBM (developer, articles/tutorials) that I recall was pretty good, however the link seems dead now.

**Comment by bluz71** [comment]
> It's time I got back to my Neovim configuration, will move to `linefly` and try the global status line.

Global `statusline` is very nice since it now provides a full screen width `statusline` for the current window (there are no inactive `statusline`s). However, you do need to enable `winbar` to disambiguate windows. `mistfly` and `linefly` both have direct options for `winbar`, which appear is little tags at the top of each window split with mode indicator and filename. You can define your own `winbar` or just use the one provided by `linefly`.

> If you have a few minutes, could you please explain what `'%*'` does?

Good question; it means `end-previous-highlighting`. `mistfly` uses coloring for some segments of the `statusline` and `%*` is a dictate to go back to the default `statusline` colors for the next segment (usually white text). `'%#MistflyNormalEmphasis#'` opens up coloring (using `MistflyNormalEmphasis` highlight group), and `%*` is used to end that coloring.

Looking at the `mistfly` code, I think through cut-n-paste `%*` is used far too much. I will audit and trim the usages back.

Good catch.

> Would you happen to have a good resource or reference for Vim script? Half a year ago I found a guide at IBM (developer, articles/tutorials) that I recall was pretty good, however the link seems dead now.

An implied assumption is that I know Vimscript.
I know just enough to barely get by (and I forget it quickly too).
Nonetheless I have used these resources:

- [Vim scripting cheats](https://devhints.io/vimscript)
- [Vim Script for the JavaScripter](https://w0rp.com/blog/post/vim-script-for-the-javascripter/) (written by the lead developer of ALE plugin)
- ChatGPT (quite useful for answering questions, including Vimscript)

I am a Neovim person, and I completely switched my entire setup to Lua last year. So that's another language to keep on top of. But in all honesty, Lua is a far better language than Vimscript. A little bit more verbose, but less quirky.

Side note, with Bram Moolenaar's very sad passing the Vim side of the equation looks uncertain (from my vista).

**Comment by bobbleclank** [comment]
Thanks. Looking forward to trying the global `statusline` with `winbar`.

> Good question; it means `end-previous-highlighting`

Ah ha. Thank you! My subpar search skills failed to solve my curiosity.

> Looking at the mistfly code, I think through cut-n-paste %* is used far too much.

I added to that, trying my best not to break its usage :)

> I will audit and trim the usages back.

I saw the cleanup. Nice.

> Nonetheless I have used these (Vimscript) resources...

Cool. Much appreciated. Seems that it's time I tried out ChatGPT; I've been holding off.

> I completely switched my entire setup to Lua

That is on my dot files to-do list. Although every time I check someone's Neovim Lua configuration, I 'holy heck' out loud.

**Comment by bluz71** [comment]
> Cool. Much appreciated. Seems that it's time I tried out ChatGPT; I've been holding off.

It is just another tool; sometimes it is useful, other times ChatGPT will actually lie.
I found it best to give it very short simple questions rather than bigger programming problems.
I use it like a personal StackOverflow, with the notion that ChatGPT could be lying to you (maybe around 30% of the time).

> That is on my dot files to-do list. Although every time I check someone's Neovim Lua configuration, I 'holy heck' out loud.

If it is of any interest I converted my Vim (in Vimscript) setup over to Neovim (in Lua) and kept both in my `dotfiles`:

- [Vim vimrc](https://github.com/bluz71/dotfiles/blob/master/vimrc) and [vim folder](https://github.com/bluz71/dotfiles/tree/master/vim)
- [Neovim init](https://github.com/bluz71/dotfiles/blob/master/nvim/init.lua) and [nvim folder](https://github.com/bluz71/dotfiles/tree/master/nvim)

Note, legacy Vimscript will always be supported in Neovim, so no harm in keeping a working setup. There are better ways to spend time.

**Comment by bobbleclank** [comment]
> It is just another tool

We had a presentation on tools like Copilot. Got to welcome these tools, rather than hide.

> If it is of any interest I converted my Vim (in Vimscript) setup over to Neovim (in Lua)

For sure it is. Thanks!

> There are better ways to spend time.

Ha, yeah. Although it must be satisfying once switched over. Plus the recent plugins seem to only have the Lua configuration example; although wrapping with `lua << EOF ... EOF` continues to work for me.

**Pull request merged**
